[package]
name = "rust-gb"
version = "0.0.1"
edition = "2021"
authors = ["zlfn <ung@zlfn.space>"]
readme = "README.md"
description = """
Compile Rust code to Nintendo GameBoy
"""

# rust-gb library
[lib]
name = "gb"
path = "src/lib/lib.rs"

# rust-gb compiler
[[bin]]
name = "cargo-build-rom"
path = "src/bin/build-rom/main.rs"
required-features = ["compiler"]

[dependencies]
clap = { version = "4.5.17", features = ["derive"], optional = true }
colored = { version = "2.1.0", optional = true }
project-root = { version = "0.2.2", optional = true }
tree-sitter = { version = "0.23.0", optional = true }
tree-sitter-c = { version = "0.23.0", optional = true }

[features]
# default = ["compiler"]
# compiler feature
compiler = ["clap", "colored", "project-root", "tree-sitter", "tree-sitter-c"]
# library feature
prototype = []
