[build]
target = "avr-unknown-gnu-atmega328"
rustflags = ["--emit=llvm-ir", "--cfg", "no_fp_fmt_parse"]

[unstable]
build-std = ["core", "alloc"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
